pipeline:
  name: Deploy Static HTML Site
  identifier: Deploy_Static_HTML_Site
  projectIdentifier: autogen-project
  orgIdentifier: default
  stages:
    - stage:
        name: Build and Deploy
        identifier: Build_Deploy
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: Checkout Code
                  identifier: Checkout_Code
                  type: GitOps
                  spec:
                    connectorRef: github_connector
                    repositoryName: autogen-harness-agent
                    branch: main
              - step:
                  name: Verify index.html
                  identifier: Verify_Index_HTML
                  type: ShellScript
                  spec:
                    shell: Bash
                    command: |
                      if [ ! -f ./index.html ]; then
                        echo "Error: index.html does not exist!"
                        exit 1
                      else
                        echo "index.html exists."
                      fi
              - step:
                  name: Push Changes
                  identifier: Push_Changes
                  type: GitOps
                  spec:
                    connectorRef: github_connector
                    repositoryName: autogen-harness-agent
                    branch: main
                    commitMessage: "Automated deployment of static HTML site"
