pipeline:
  name: Static_HTML_Site_Deployment
  identifier: StaticHTMLDeployment
  stages:
    - stage:
        name: Build_and_Deploy
        identifier: BuildAndDeploy
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: Checkout Code
                  identifier: CheckoutCode
                  type: GitClone
                  spec:
                    connectorRef: my_github_connector
                    repoName: my_static_site_repo
                    branch: main
              - step:
                  name: Verify Index.html Exists
                  identifier: VerifyIndexHtml
                  type: ShellScript
                  spec:
                    shell: Bash
                    source:
                      type: Inline
                      spec:
                        script: |
                          if [ ! -f index.html ]; then
                            echo "Error: index.html not found!"
                            exit 1
                          fi
              - step:
                  name: Push Changes
                  identifier: PushChanges
                  type: ShellScript
                  spec:
                    shell: Bash
                    source:
                      type: Inline
                      spec:
                        script: |
                          git config user.email "change-email@example.com"
                          git config user.name "Change Name"
                          git add index.html
                          git commit -m "Ensured index.html exists"
                          git push origin main